apiVersion: v1
kind: Service
metadata:
  name: forecastappfeature
  namespace: forecastappfeature
spec:
  selector:
    app: forecastappfeature
  ports:
    - name: http
      port: 8080
      targetPort: http